services:
  channelemojis:
    container_name: channelemojis
    build: .
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - NODE_ENV=production
    restart: unless-stopped
    volumes:
      - ./:/channelemojis